/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MainEstimateDealBody
 */
public class MainEstimateDealBodyTest {
    private final MainEstimateDealBody model = new MainEstimateDealBody();

    /**
     * Model tests for MainEstimateDealBody
     */
    @Test
    public void testMainEstimateDealBody() {
        // TODO: test MainEstimateDealBody
    }

    /**
     * Test the property 'durationBlks'
     */
    @Test
    public void durationBlksTest() {
        // TODO: test durationBlks
    }

    /**
     * Test the property 'replication'
     */
    @Test
    public void replicationTest() {
        // TODO: test replication
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'verified'
     */
    @Test
    public void verifiedTest() {
        // TODO: test verified
    }

}
