/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MainUserStatsResponse
 */
public class MainUserStatsResponseTest {
    private final MainUserStatsResponse model = new MainUserStatsResponse();

    /**
     * Model tests for MainUserStatsResponse
     */
    @Test
    public void testMainUserStatsResponse() {
        // TODO: test MainUserStatsResponse
    }

    /**
     * Test the property 'numPins'
     */
    @Test
    public void numPinsTest() {
        // TODO: test numPins
    }

    /**
     * Test the property 'totalSize'
     */
    @Test
    public void totalSizeTest() {
        // TODO: test totalSize
    }

}
