/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * MainEstimateDealBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-28T23:49:15.047006Z[Etc/UTC]")
public class MainEstimateDealBody {
  public static final String SERIALIZED_NAME_DURATION_BLKS = "durationBlks";
  @SerializedName(SERIALIZED_NAME_DURATION_BLKS)
  private Integer durationBlks;

  public static final String SERIALIZED_NAME_REPLICATION = "replication";
  @SerializedName(SERIALIZED_NAME_REPLICATION)
  private Integer replication;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private Integer size;

  public static final String SERIALIZED_NAME_VERIFIED = "verified";
  @SerializedName(SERIALIZED_NAME_VERIFIED)
  private Boolean verified;

  public MainEstimateDealBody() { 
  }

  public MainEstimateDealBody durationBlks(Integer durationBlks) {
    
    this.durationBlks = durationBlks;
    return this;
  }

   /**
   * Get durationBlks
   * @return durationBlks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDurationBlks() {
    return durationBlks;
  }


  public void setDurationBlks(Integer durationBlks) {
    this.durationBlks = durationBlks;
  }


  public MainEstimateDealBody replication(Integer replication) {
    
    this.replication = replication;
    return this;
  }

   /**
   * Get replication
   * @return replication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReplication() {
    return replication;
  }


  public void setReplication(Integer replication) {
    this.replication = replication;
  }


  public MainEstimateDealBody size(Integer size) {
    
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSize() {
    return size;
  }


  public void setSize(Integer size) {
    this.size = size;
  }


  public MainEstimateDealBody verified(Boolean verified) {
    
    this.verified = verified;
    return this;
  }

   /**
   * Get verified
   * @return verified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getVerified() {
    return verified;
  }


  public void setVerified(Boolean verified) {
    this.verified = verified;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MainEstimateDealBody mainEstimateDealBody = (MainEstimateDealBody) o;
    return Objects.equals(this.durationBlks, mainEstimateDealBody.durationBlks) &&
        Objects.equals(this.replication, mainEstimateDealBody.replication) &&
        Objects.equals(this.size, mainEstimateDealBody.size) &&
        Objects.equals(this.verified, mainEstimateDealBody.verified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(durationBlks, replication, size, verified);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MainEstimateDealBody {\n");
    sb.append("    durationBlks: ").append(toIndentedString(durationBlks)).append("\n");
    sb.append("    replication: ").append(toIndentedString(replication)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("durationBlks");
    openapiFields.add("replication");
    openapiFields.add("size");
    openapiFields.add("verified");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MainEstimateDealBody
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (MainEstimateDealBody.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in MainEstimateDealBody is not found in the empty JSON string", MainEstimateDealBody.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!MainEstimateDealBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MainEstimateDealBody` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MainEstimateDealBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MainEstimateDealBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MainEstimateDealBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MainEstimateDealBody.class));

       return (TypeAdapter<T>) new TypeAdapter<MainEstimateDealBody>() {
           @Override
           public void write(JsonWriter out, MainEstimateDealBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MainEstimateDealBody read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MainEstimateDealBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MainEstimateDealBody
  * @throws IOException if the JSON string is invalid with respect to MainEstimateDealBody
  */
  public static MainEstimateDealBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MainEstimateDealBody.class);
  }

 /**
  * Convert an instance of MainEstimateDealBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

