/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UtilContentAddIpfsBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-28T23:49:15.047006Z[Etc/UTC]")
public class UtilContentAddIpfsBody {
  public static final String SERIALIZED_NAME_COLLECTION = "collection";
  @SerializedName(SERIALIZED_NAME_COLLECTION)
  private String collection;

  public static final String SERIALIZED_NAME_COLLECTION_PATH = "collectionPath";
  @SerializedName(SERIALIZED_NAME_COLLECTION_PATH)
  private String collectionPath;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PEERS = "peers";
  @SerializedName(SERIALIZED_NAME_PEERS)
  private List<String> peers = null;

  public static final String SERIALIZED_NAME_ROOT = "root";
  @SerializedName(SERIALIZED_NAME_ROOT)
  private String root;

  public UtilContentAddIpfsBody() { 
  }

  public UtilContentAddIpfsBody collection(String collection) {
    
    this.collection = collection;
    return this;
  }

   /**
   * Get collection
   * @return collection
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCollection() {
    return collection;
  }


  public void setCollection(String collection) {
    this.collection = collection;
  }


  public UtilContentAddIpfsBody collectionPath(String collectionPath) {
    
    this.collectionPath = collectionPath;
    return this;
  }

   /**
   * Get collectionPath
   * @return collectionPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCollectionPath() {
    return collectionPath;
  }


  public void setCollectionPath(String collectionPath) {
    this.collectionPath = collectionPath;
  }


  public UtilContentAddIpfsBody name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public UtilContentAddIpfsBody peers(List<String> peers) {
    
    this.peers = peers;
    return this;
  }

  public UtilContentAddIpfsBody addPeersItem(String peersItem) {
    if (this.peers == null) {
      this.peers = new ArrayList<>();
    }
    this.peers.add(peersItem);
    return this;
  }

   /**
   * Get peers
   * @return peers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPeers() {
    return peers;
  }


  public void setPeers(List<String> peers) {
    this.peers = peers;
  }


  public UtilContentAddIpfsBody root(String root) {
    
    this.root = root;
    return this;
  }

   /**
   * Get root
   * @return root
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRoot() {
    return root;
  }


  public void setRoot(String root) {
    this.root = root;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UtilContentAddIpfsBody utilContentAddIpfsBody = (UtilContentAddIpfsBody) o;
    return Objects.equals(this.collection, utilContentAddIpfsBody.collection) &&
        Objects.equals(this.collectionPath, utilContentAddIpfsBody.collectionPath) &&
        Objects.equals(this.name, utilContentAddIpfsBody.name) &&
        Objects.equals(this.peers, utilContentAddIpfsBody.peers) &&
        Objects.equals(this.root, utilContentAddIpfsBody.root);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collection, collectionPath, name, peers, root);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UtilContentAddIpfsBody {\n");
    sb.append("    collection: ").append(toIndentedString(collection)).append("\n");
    sb.append("    collectionPath: ").append(toIndentedString(collectionPath)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    peers: ").append(toIndentedString(peers)).append("\n");
    sb.append("    root: ").append(toIndentedString(root)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("collection");
    openapiFields.add("collectionPath");
    openapiFields.add("name");
    openapiFields.add("peers");
    openapiFields.add("root");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UtilContentAddIpfsBody
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (UtilContentAddIpfsBody.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in UtilContentAddIpfsBody is not found in the empty JSON string", UtilContentAddIpfsBody.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!UtilContentAddIpfsBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UtilContentAddIpfsBody` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("collection") != null && !jsonObj.get("collection").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `collection` to be a primitive type in the JSON string but got `%s`", jsonObj.get("collection").toString()));
      }
      if (jsonObj.get("collectionPath") != null && !jsonObj.get("collectionPath").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `collectionPath` to be a primitive type in the JSON string but got `%s`", jsonObj.get("collectionPath").toString()));
      }
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the json data is an array
      if (jsonObj.get("peers") != null && !jsonObj.get("peers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `peers` to be an array in the JSON string but got `%s`", jsonObj.get("peers").toString()));
      }
      if (jsonObj.get("root") != null && !jsonObj.get("root").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `root` to be a primitive type in the JSON string but got `%s`", jsonObj.get("root").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UtilContentAddIpfsBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UtilContentAddIpfsBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UtilContentAddIpfsBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UtilContentAddIpfsBody.class));

       return (TypeAdapter<T>) new TypeAdapter<UtilContentAddIpfsBody>() {
           @Override
           public void write(JsonWriter out, UtilContentAddIpfsBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UtilContentAddIpfsBody read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UtilContentAddIpfsBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UtilContentAddIpfsBody
  * @throws IOException if the JSON string is invalid with respect to UtilContentAddIpfsBody
  */
  public static UtilContentAddIpfsBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UtilContentAddIpfsBody.class);
  }

 /**
  * Convert an instance of UtilContentAddIpfsBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

