/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.MainAddContentToCollectionParams;
import org.openapitools.client.model.MainCollection;
import org.openapitools.client.model.MainCreateCollectionBody;
import org.openapitools.client.model.UtilHttpError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CollectionsApi
 */
@Disabled
public class CollectionsApiTest {

    private final CollectionsApi api = new CollectionsApi();

    /**
     * Add contents to a collection
     *
     * When a collection is created, users with valid API keys can add contents to the collection. This endpoint can be used to add contents to a collection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void collectionsAddContentPostTest() throws ApiException {
        MainAddContentToCollectionParams body = null;
        Map<String, String> response = api.collectionsAddContentPost(body);
        // TODO: test validations
    }

    /**
     * Get contents in a collection
     *
     * This endpoint is used to get contents in a collection. When a collection is created, this collection object is retrievable along with its content via this endpoint.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void collectionsContentColuuidGetTest() throws ApiException {
        String coluuid = null;
        String response = api.collectionsContentColuuidGet(coluuid);
        // TODO: test validations
    }

    /**
     * Create a new collection
     *
     * This endpoint is used to create a new collection. A collection is a representaion of a group of objects added on the estuary. This endpoint can be used to create a new collection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void collectionsCreatePostTest() throws ApiException {
        MainCreateCollectionBody body = null;
        MainCollection response = api.collectionsCreatePost(body);
        // TODO: test validations
    }

    /**
     * Add a file to a collection
     *
     * This endpoint adds a file to a collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void collectionsFsAddPostTest() throws ApiException {
        String col = null;
        String collection = null;
        String content = null;
        String path = null;
        String response = api.collectionsFsAddPost(col, collection, content, path);
        // TODO: test validations
    }

    /**
     * Create a new collection
     *
     * This endpoint creates a new collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void collectionsFsListGetTest() throws ApiException {
        String col = null;
        String dir = null;
        String response = api.collectionsFsListGet(col, dir);
        // TODO: test validations
    }

    /**
     * List all collections
     *
     * This endpoint is used to list all collections. Whenever a user logs on estuary, it will list all collections that the user has access to. This endpoint provides a way to list all collections to the user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void collectionsListGetTest() throws ApiException {
        List<MainCollection> response = api.collectionsListGet();
        // TODO: test validations
    }

}
