/*
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.UtilHttpError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PinningApi
 */
@Disabled
public class PinningApiTest {

    private final PinningApi api = new PinningApi();

    /**
     * List all pinned objects
     *
     * This endpoint lists all pinned objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pinningPinsGetTest() throws ApiException {
        api.pinningPinsGet();
        // TODO: test validations
    }

    /**
     * Add and pin object
     *
     * This endpoint adds a pin to the IPFS daemon.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pinningPinsPostTest() throws ApiException {
        String cid = null;
        String name = null;
        String response = api.pinningPinsPost(cid, name);
        // TODO: test validations
    }

    /**
     * Delete a pinned object
     *
     * This endpoint deletes a pinned object.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pinningPinsRequestidDeleteTest() throws ApiException {
        String requestid = null;
        String response = api.pinningPinsRequestidDelete(requestid);
        // TODO: test validations
    }

    /**
     * Get a pinned objects
     *
     * This endpoint returns a pinned object.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pinningPinsRequestidGetTest() throws ApiException {
        String requestid = null;
        String response = api.pinningPinsRequestidGet(requestid);
        // TODO: test validations
    }

    /**
     * Replace a pinned object
     *
     * This endpoint replaces a pinned object.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pinningPinsRequestidPostTest() throws ApiException {
        String requestid = null;
        String response = api.pinningPinsRequestidPost(requestid);
        // TODO: test validations
    }

}
